version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    volumes:
      - C:\Users\lucas.flor\Desktop\docker\rabbitmq\data:/var/lib/rabbitmq
    ports:
      - 15672:15672